const navbar=document.getElementById('navbar'),progress=document.getElementById('progress'),menuToggle=document.getElementById('menuToggle'),navMenu=document.getElementById('navMenu');
window.addEventListener('scroll',()=>{if(navbar)navbar.classList.toggle('scrolled',window.scrollY>30);if(progress){const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=(max>0?(window.scrollY/max)*100:0)+'%'}});
if(menuToggle&&navMenu){menuToggle.addEventListener('click',()=>navMenu.classList.toggle('open'));document.querySelectorAll('#navMenu a').forEach(a=>a.addEventListener('click',()=>navMenu.classList.remove('open')))}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
function increment(key){localStorage.setItem(key,(parseInt(localStorage.getItem(key)||'0',10)+1).toString())}
if(location.pathname.endsWith('index.html')||location.pathname.endsWith('/')){increment('mm_visits');const v=document.getElementById('visitCount');if(v)v.textContent=localStorage.getItem('mm_visits');}
const commentForm=document.getElementById('commentForm'),commentList=document.getElementById('commentList');
function renderComments(){if(!commentList)return;const data=JSON.parse(localStorage.getItem('mm_comments')||'[]');commentList.innerHTML=data.map(c=>`<div class="comment-item"><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.date)}</small><p>${escapeHtml(c.text)}</p></div>`).join('');const cc=document.getElementById('commentCount');if(cc)cc.textContent=data.length}
function escapeHtml(s){return s.replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
if(commentForm){renderComments();commentForm.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('commentName').value.trim(),text=document.getElementById('commentText').value.trim();if(!name||!text)return;const data=JSON.parse(localStorage.getItem('mm_comments')||'[]');data.unshift({name,text,date:new Date().toLocaleString('id-ID')});localStorage.setItem('mm_comments',JSON.stringify(data.slice(0,30)));commentForm.reset();renderComments()})}
const shareButton=document.getElementById('shareButton');if(shareButton)shareButton.addEventListener('click',()=>sharePage('Website Miftahul Munir, S.E. — Inspirasi & Motivasi'));
const articleShare=document.getElementById('articleShare');if(articleShare){increment('mm_articles');const r=document.getElementById('readingCount');if(r)r.textContent=localStorage.getItem('mm_articles');articleShare.addEventListener('click',()=>sharePage('Artikel Motivasi Miftahul Munir, S.E.'))}
async function sharePage(title){if(navigator.share){try{await navigator.share({title,text:title,url:location.href})}catch(e){}}else{await navigator.clipboard?.writeText(location.href);alert('Tautan website sudah disalin.')}}
